# Generated by Django 5.0.6 on 2024-08-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brands',
            new_name='brand',
        ),
    ]
